export const coachableSports = {
  baseball: "Baseball",
  basketball: "Basketball",
  crossCountry: "Cross Country",
  football: "Football",
  golf: "Golf",
  gymnastics: "Gymnastics",
  pickleball: "Pickleball",
  soccer: "Soccer",
  softball: "Softball",
  swimming: "Swimming",
  tennis: "Tennis",
  track: "Track",
  volleyball: "Volleyball",
};
